# This is a basic workflow to help you get started with Actions

name: Build Docker container

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Build minimal container
    runs-on: windows-2019

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Docker container
      run: |
        docker build -f Dockerfile -t cwuensch/avisynth:2.60 .
      
    - name: Push Docker container 
      run: |
        docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
        docker push cwuensch/avisynth:2.60

  test:
    name: Test Docker container
    runs-on: windows-2019
    needs: build

    steps:
    - name: Start Docker container
      run: |
        docker run --rm -v ${{ github.workspace }}:C:/source/ --workdir "C:/source" cwuensch/avisynth:2.60 "Demo.avs" /s Recompress_UTVideo.vcf /x

    - name: Copy build artefact
      uses: actions/upload-artifact@v2
      with:
        name: Video_out
        path: |
          ${{ github.workspace }}/Video_out.avi
